version: '1.0'
services:

  ecommerce-eureka-discovery-server:
    container_name: ecommerce-eureka-discovery-server
    image: ecommerce-discovery-server-image
    ports:
      - 8761:8761

  ecommerce-platform-database-container:
    container_name: ecommerce-platform-database-container
    image: container-registry.oracle.com/database/express:latest
    environment:
      - ORACLE_PWD=asen311
    ports:
      - 1523:1521
      - 5501:5500
    volumes:
      - ecommerce-platform-database_volume:/opt/oracle/oradata

  ecommerce-back-office-database-container:
    container_name: ecommerce-back-office-database-container
    image: container-registry.oracle.com/database/express:latest
    environment:
      - ORACLE_PWD=asen311
    ports:
      - 1522:1521
      - 5502:5500
    volumes:
      - ecommerce-platform-back-office-database_volume:/opt/oracle/oradata


  ecommerce-back-office-service:
    container_name: ecommerce-back-office-service
    image: ecommerce-back-office-service-image
    ports:
      - 8087:8087
    depends_on:
      - ecommerce-back-office-database-container
      - ecommerce-eureka-discovery-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@ecommerce-back-office-database-container:1521:xe
      - SPRING_DATASOURCE_USERNAME=ec_back_office
      - SPRING_DATASOURCE_PASSWORD=ec_back_office
      - EUREKA_CLIENT_SERVICE_URL=http://ecommerce-eureka-discovery-server:8761/eureka/

  ecommerce-platform-service:
    container_name: ecommerce-platform-service
    image: ecommerce-platform-image
    ports:
      - 8086:8086
    depends_on:
      - ecommerce-platform-database-container
      - ecommerce-eureka-discovery-server
      - ecommerce-back-office-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@ecommerce-platform-database-container:1521:xe
      - SPRING_DATASOURCE_USERNAME=ec_platform
      - SPRING_DATASOURCE_PASSWORD=ec_platform
      - EUREKA_CLIENT_SERVICE_URL=http://ecommerce-eureka-discovery-server:8761/eureka/

volumes:
  ecommerce-platform-back-office-database_volume:
    driver: local
    driver_opts:
      type: none
      device: C:/oracle/ecommerce-back-office/oradata
      o: bind
  ecommerce-platform-database_volume:
    driver: local
    driver_opts:
      type: none
      device: C:/oracle/ecommerceplatform/oradata
      o: bind
